name: test-post
on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # ← cache は付けない

      - name: Show versions
        run: |
          python --version
          pip --version

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install requests openai

      - name: Run script
        env:
          RAKUTEN_APP_ID:       ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.RAKUTEN_AFFILIATE_ID }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          TW_CLIENT_ID:         ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET:     ${{ secrets.TW_CLIENT_SECRET }}
          TW_REFRESH_TOKEN:     ${{ secrets.TW_REFRESH_TOKEN }}
        run: |
          python -u post_picture_book.py
