name: test-post

on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write   # Secret 更新に必要

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install "requests>=2.31.0" "openai>=1.35.0"

      - id: post
        env:
          RAKUTEN_APP_ID:       ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.RAKUTEN_AFFILIATE_ID }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          TW_CLIENT_ID:         ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET:     ${{ secrets.TW_CLIENT_SECRET }}
          TW_REFRESH_TOKEN:     ${{ secrets.TW_REFRESH_TOKEN }}
        run: |
          python post_picture_book.py

      - name: Update TW_REFRESH_TOKEN secret (if rotated)
        if: ${{ steps.post.outputs.new_refresh_token != '' }}
        uses: peter-evans/create-or-update-secret@v3
        with:
          token: ${{ github.token }}
          secret-name: TW_REFRESH_TOKEN
          secret-value: ${{ steps.post.outputs.new_refresh_token }}
