name: test-post
on:
  workflow_dispatch: {}
  schedule:
    # UTC で指定。JST 07:30 / 12:30 / 20:30 相当
    - cron: '30 22 * * *'  # 07:30 JST
    - cron: '30 03 * * *'  # 12:30 JST
    - cron: '30 11 * * *'  # 20:30 JST

permissions:
  actions: write
  contents: write   # 履歴ファイルのコミットに必要

concurrency:
  group: post-ehon
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -U requests openai

      - name: Run script
        id: post
        env:
          RAKUTEN_APP_ID:       ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.RAKUTEN_AFFILIATE_ID }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          TW_CLIENT_ID:         ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET:     ${{ secrets.TW_CLIENT_SECRET }}
          TW_REFRESH_TOKEN:     ${{ secrets.TW_REFRESH_TOKEN }}
          # 重複禁止期間（日）と履歴ファイルパス
          DEDUP_DAYS: "120"
          POST_HISTORY_PATH: "data/posted_history.json"
        run: python -u post_picture_book.py

      # 履歴をコミット（変更があるときだけ）
      - name: Commit post history
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: record posted book [skip ci]"
          file_pattern: data/posted_history.json
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com

      # refresh_token がローテされたら Secrets を更新
      - name: Update TW_REFRESH_TOKEN secret (if rotated)
        if: steps.post.outputs.new_refresh_token != ''
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # repo 権限の PAT（SSO 承認済み）
        run: |
          echo "Rotating TW_REFRESH_TOKEN..."
          gh secret set TW_REFRESH_TOKEN \
            --repo "$GITHUB_REPOSITORY" \
            --body "${{ steps.post.outputs.new_refresh_token }}"
