name: test-post
on:
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write   # ← Secret 更新で必要

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests openai

      - id: post
        env:
          RAKUTEN_APP_ID:       ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.RAKUTEN_AFFILIATE_ID }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          TW_CLIENT_ID:         ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET:     ${{ secrets.TW_CLIENT_SECRET }}
          TW_REFRESH_TOKEN:     ${{ secrets.TW_REFRESH_TOKEN }}
        run: |
          python - <<'PY'
          # ここはあなたの post_picture_book.py の中身（new_refresh_token を stdout へ）
          # 最後に new_refresh_token を出力したい時だけ print する。
          # 出力例: print("NEW_REFRESH_TOKEN=xxxxx") など
          PY

      # もし上のステップで new_refresh_token を標準出力に流せない場合は
      # python 側で GITHUB_OUTPUT に書く方式にして、
      # `outputs:` で受け取ってください（下の uses 部には id.post.outputs... を指定）

      - name: Update TW_REFRESH_TOKEN secret (if rotated)
        if: ${{ steps.post.outputs.new_refresh_token != '' }}
        uses: peter-evans/create-or-update-secret@v3
        with:
          token: ${{ github.token }}              # ← GITHUB_TOKEN でOK
          secret-name: TW_REFRESH_TOKEN
          secret-value: ${{ steps.post.outputs.new_refresh_token }}
