name: test-post
on:
  workflow_dispatch: {}

permissions:
  actions: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -U requests openai beautifulsoup4 lxml

      # 実行（デバッグ環境変数は必要に応じて調整）
      - name: Run script
        id: post
        env:
          RAKUTEN_APP_ID:       ${{ secrets.RAKUTEN_APP_ID }}
          RAKUTEN_AFFILIATE_ID: ${{ secrets.RAKUTEN_AFFILIATE_ID }}
          OPENAI_API_KEY:       ${{ secrets.OPENAI_API_KEY }}
          TW_CLIENT_ID:         ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET:     ${{ secrets.TW_CLIENT_SECRET }}
          TW_REFRESH_TOKEN:     ${{ secrets.TW_REFRESH_TOKEN }}
          DEBUG: "1"
          # 固定IDで検証したいときだけ一時的に使う（例: 138019）
          # EHONNAVI_ID_FORCE: "138019"
          # ランダム範囲や試行回数を変えたい場合
          # EHONNAVI_ID_RANGE: "10000-400000"
          # EHONNAVI_TRIES: "20"
        run: |
          python -u post_picture_book.py

      # 解析用のデータを常に回収（存在しなければ無視）
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-ehonnavi-rakuten
          path: |
            /tmp/ehonnavi_pick.html
            /tmp/rakuten_search_title.json
            /tmp/rakuten_search_keyword.json
          if-no-files-found: ignore

      # 返ってきた new_refresh_token があれば Secrets を更新
      - name: Update TW_REFRESH_TOKEN secret (if rotated)
        if: steps.post.outputs.new_refresh_token != ''
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}   # repo 権限の PAT（SSO 承認済み）
        run: |
          echo "Rotating TW_REFRESH_TOKEN..."
          gh auth status
          gh secret set TW_REFRESH_TOKEN \
            --repo "$GITHUB_REPOSITORY" \
            --body "${{ steps.post.outputs.new_refresh_token }}"
